### ISSUE TITLE
chromium config is missing

### ISSUE THREAD

**Issue by ashnur** [james-proxy/james-browser-launcher#65]
trying to use "chromium" browser, which is detected by 
```
➜  james-browser-launcher git:(master) ✗ node example/detect.js
Available browsers:
[ { name: 'chromium',
    version: '59.0.3071.115',
    type: 'chromium',
    command: 'chromium' } ]
```
results in
`TypeError: setups[browser.type] is not a function`

**Comment by mitchhentges** [comment]
Thanks for the report! [Fixed and released in `1.3.1`](https://github.com/james-proxy/james-browser-launcher/blob/master/CHANGELOG.md#131)
