### ISSUE TITLE
Deprecate npm package james-browser-launcher

### ISSUE THREAD

**Issue by nerdbeere** [james-proxy/james-browser-launcher#77]
Hi @mitchhentges 
could you deprecate the npm package `james-browser-launcher` in favor of `@james-proxy/james-browser-launcher`?

This is what I did with `joxy`: 
```
npm deprecate joxy "joxy is now part of @james-proxy org, use @james-proxy/joxy instead"
```

**Comment by mitchhentges** [comment]
Done :+1:
